export const questionObject = [
    {
        question: "Which country invented ice cream?",
        choiceA: "Egypt",
        choiceB: "Italy",
        choiceC: "Turkey",
        choiceD: "China",
        answer: "China",
    },
    {
        question: "how long is an Olympic Swimming pool?",
        choiceA: "35m",
        choiceB: "100m",
        choiceC: "50m",
        choiceD: "25m",
        answer: "50m",
    },
    {
        question: "What is the smallest country in the world?",
        choiceA: "Vatican City",
        choiceB: "Monaco",
        choiceC: "Maldives",
        choiceD: "Malta",
        answer: "Vatican City",
    },
    {
        question: "Which African animal has a name that means 'river horse'?",
        choiceA: "Wildebeest",
        choiceB: "African Buffalo",
        choiceC: "Hippopotamus",
        choiceD: "Kobs",
        answer: "Hippopotamus",
    },
    {
        question: "What is the world's most expensive spice by weight?",
        choiceA: "Fennel Pollen",
        choiceB: "Kaffir Lime",
        choiceC: "Saffron",
        choiceD: "Vanilla Bean",
        answer: "Saffron",
    },
    {
        question: "What was the first toy to be advertised on TV",
        choiceA: "Barbie",
        choiceB: "Mr Potato Head",
        choiceC: "Cabbage Patch Dolls",
        choiceD: "GameBoy",
        answer: "Mr Potato Head",
    },
    {
        question: "What is Flynn Rider's real name in Disney's Tangled?",
        choiceA: "John Smith",
        choiceB: "Hans  Fitzgerald",
        choiceC: "Hubert Rolfe",
        choiceD: "Eugene Fitzherbet",
        answer: "Eugene Fitzherbet",
    },
    {
        question: "The Egyptian God Anubis has the head of which animal?",
        choiceA: "Scarab Beetle",
        choiceB: "Jackal",
        choiceC: "Horse",
        choiceD: "Lion",
        answer: "Jackal",
    },
    {
        question: "In which US state is Are 51 located?",
        choiceA: "California",
        choiceB: "Maine",
        choiceC: "Alaska",
        choiceD: "Nevada",
        answer: "Nevada",
    },
    {
        question: "What are the only two mammals known to lay eggs?",
        choiceA: "Anteater & Duck-billed Platypus",
        choiceB: "Anteater & Seahorse",
        choiceC: "Duck-billed Platypus & Seahorse",
        choiceD: "None of the above",
        answer: "Anteater & Duck-billed Platypus",
    },
    {
        question: "Who framed Roger Rabbit?",
        choiceA: "Eddie Valiant",
        choiceB: "RK Maroon",
        choiceC: "Judge Doom",
        choiceD: "Jessica Rabbit",
        answer: "Judge Doom",
    },
    {
        question: "Which of these films did John Williams not compose for?",
        choiceA: "Jaws",
        choiceB: "Jurassic Park",
        choiceC: "Home Alone",
        choiceD: "The Dark Knight",
        answer: "The Dark Knight",
    },
    {
        question: "In which famous museum does a murder take place at the start of Da Vinci Code by Dan Brown?",
        choiceA: "The Louvre",
        choiceB: "National History Museum",
        choiceC: "The Museum of Modern Art",
        choiceD: "The National Gallery",
        answer: "The Louvre",
    },
    {
        question: "In what novel did Arthur Conan Doyle's Sherlock Holmes character first appear?",
        choiceA: "The Valley of Fear",
        choiceB: "The Hound of the Baskervilles",
        choiceC: "A Study in Scarlet",
        choiceD: "The Sign of the Four" ,
        answer: "A Study in Scarlet",
    },
    {
        question: "Who wrote The Fellowship of the Ring, the first book in a popular fantasy trilogy?",
        choiceA: "J. R. R. Tolkien",
        choiceB: "J. R. K. Tolkien",
        choiceC: "J. K. R. Tolkien",
        choiceD: "J. K. K. Tolkien",
        answer: "J. R. R. Tolkien",
    },
    {
        question: "how many time zones are there in Russia?",
        choiceA: "8",
        choiceB: "9",
        choiceC: "10",
        choiceD: "11",
        answer: "11",
    },
    {
        question: "Which of these chillis is the hottest on the Scoville scale?",
        choiceA: "Jalapeno",
        choiceB: "Carolina Reaper",
        choiceC: "Scotch Bonnet",
        choiceD: "Habanero",
        answer: "Carolina Reaper",
    },
    {
        question: "How many labours did Hercules have to complete?",
        choiceA: "3",
        choiceB: "7",
        choiceC: "12",
        choiceD: "9",
        answer: "12",
    },
    {
        question: "Which of these creatures was not alive during the Jurassic period? ",
        choiceA: "Tyrannosaurus",
        choiceB: "Stegosaurus",
        choiceC: "Brachiosurus",
        choiceD: "Diplodocus",
        answer: "Tyrannosaurus",
    },
    {
        question: "How many ribs are there in the human body?",
        choiceA: "26",
        choiceB: "22",
        choiceC: "24",
        choiceD: "28",
        answer: "24",
    },
]
